# Generated by Django 3.2.10 on 2023-12-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('custom', '0001_initial')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('activity', models.IntegerField(default=1)),
                ('trade', models.IntegerField(default=1000)),
                ('total_roi', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(blank=True, choices=[('BTC', 'bitcoin'), ('ETH', 'etherum'), ('SOL', 'solana'), ('BNB', 'binance')], max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MAle'), ('F', 'FEMALE')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('total_deposited', models.IntegerField(blank=True, default=0, null=True)),
                ('total_withdrawn', models.IntegerField(blank=True, default=0, null=True)),
                ('stake', models.IntegerField(blank=True, default=0, null=True)),
                ('trade', models.IntegerField(blank=True, default=0, null=True)),
                ('plan_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('isPremium', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('time_of_transaction', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Deposit', 'deposit'), ('Withdrawal', 'withdrawal')], max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositor', to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('sub_type', models.CharField(blank=True, choices=[('Premium', 'Premium'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=100, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='custom.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=225, null=True)),
                ('bank', models.CharField(blank=True, max_length=225, null=True)),
                ('account_name', models.CharField(blank=True, max_length=225, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
