# Generated by Django 3.2.10 on 2023-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('activity', models.IntegerField(default=1)),
                ('trade', models.IntegerField(default=1000)),
                ('total_roi', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='primaryuser',
            name='copy_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primaryuser',
            name='sub_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primaryuser',
            name='total_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
