# Generated by Django 3.2.10 on 2023-12-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20231208_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='owner',
        ),
    ]
